# application.yaml
# Server settings (ServerProperties)
server:
  port: 8080
  sessionTimeout: 30
  contextPath: /tools

  # Tomcat specifics
  tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs